 [
      {
        "id": null,
        "date": "1641739909000",
        "ref": "CDP74584025",
        "employee": "timothy.farmyard@gmail.com",
        "paymentType": "Card",
        "amount": 11500,
        "saleType": "Entrance",
        "saleDesc": "Normal Price",
        "quantity": 2
      },
      {
        "id": null,
        "date": "1609686182000",
        "ref": "CDP34474985",
        "employee": "timothy.farmyard@gmail.com",
        "paymentType": "Card",
        "amount": 47500,
        "saleType": "Entrance",
        "saleDesc": "Discount Price",
        "quantity": 7
      },
      {
        "id": null,
        "date": "1619967379000",
        "ref": "CDP43957816",
        "employee": "timothy.farmyard@gmail.com",
        "paymentType": "Card",
        "amount": 22500,
        "saleType": "Shop",
        "saleDesc": "Shop Sales",
        "quantity": 1
      },
      {
        "id": null,
        "date": "1638110385000",
        "ref": "CHP67368194",
        "employee": "timothy.farmyard@gmail.com",
        "paymentType": "Cash",
        "amount": 17000,
        "saleType": "Entrance",
        "saleDesc": "Normal Price",
        "quantity": 2
      },
      {
        "id": null,
        "date": "1616330578000",
        "ref": "CDP39804460",
        "employee": "timothy.farmyard@gmail.com",
        "paymentType": "Card",
        "amount": 45000,
        "saleType": "Entrance",
        "saleDesc": "Normal Price",
        "quantity": 6
      },
      {
        "id": null,
        "date": "1645376461000",
        "ref": "CHP80489352",
        "employee": "timothy.farmyard@gmail.com",
        "paymentType": "Cash",
        "amount": 8500,
        "saleType": "Entrance",
        "saleDesc": "Normal Price",
        "quantity": 1
      },
      {
        "id": null,
        "date": "1612101057000",
        "ref": "CHP35804998",
        "employee": "timothy.farmyard@gmail.com",
        "paymentType": "Cash",
        "amount": 2500,
        "saleType": "Entrance",
        "saleDesc": "Discount Price",
        "quantity": 1
      },
      {
        "id": null,
        "date": "1618135233000",
        "ref": "CHP41902731",
        "employee": "timothy.farmyard@gmail.com",
        "paymentType": "Cash",
        "amount": 45000,
        "saleType": "Entrance",
        "saleDesc": "Normal Price",
        "quantity": 6
      },
      {
        "id": null,
        "date": "1639320896000",
        "ref": "CDP69567910",
        "employee": "timothy.farmyard@gmail.com",
        "paymentType": "Card",
        "amount": 28500,
        "saleType": "Entrance",
        "saleDesc": "Normal Price",
        "quantity": 4
      },
      {
        "id": null,
        "date": "1647793200000",
        "ref": "CHP84968960",
        "employee": "timothy.farmyard@gmail.com",
        "paymentType": "Cash",
        "amount": 10000,
        "saleType": "Shop",
        "saleDesc": "Shop Sales",
        "quantity": 1
      },
      {
        "id": null,
        "date": "1643552205000",
        "ref": "CHP77470535",
        "employee": "timothy.farmyard@gmail.com",
        "paymentType": "Cash",
        "amount": 28500,
        "saleType": "Entrance",
        "saleDesc": "Normal Price",
        "quantity": 4
      },
      {
        "id": null,
        "date": "1618749953000",
        "ref": "CDP42473971",
        "employee": "timothy.farmyard@gmail.com",
        "paymentType": "Card",
        "amount": 62000,
        "saleType": "Entrance",
        "saleDesc": "Normal Price",
        "quantity": 8
      },
      {
        "id": null,
        "date": "1615133824000",
        "ref": "CHP38693981",
        "employee": "timothy.farmyard@gmail.com",
        "paymentType": "Cash",
        "amount": 305500,
        "saleType": "Entrance",
        "saleDesc": "Discount Price",
        "quantity": 47
      },
      {
        "id": null,
        "date": "1613919707000",
        "ref": "CHP37339932",
        "employee": "timothy.farmyard@gmail.com",
        "paymentType": "Cash",
        "amount": 19500,
        "saleType": "Entrance",
        "saleDesc": "Normal Price",
        "quantity": 3
      },
      {
        "id": null,
        "date": "1637504521000",
        "ref": "CDP66346213",
        "employee": "timothy.farmyard@gmail.com",
        "paymentType": "Card",
        "amount": 37000,
        "saleType": "Entrance",
        "saleDesc": "Normal Price",
        "quantity": 5
      },
      {
        "id": null,
        "date": "1647170536000",
        "ref": "CHP83790822",
        "employee": "timothy.farmyard@gmail.com",
        "paymentType": "Cash",
        "amount": 28500,
        "saleType": "Entrance",
        "saleDesc": "Normal Price",
        "quantity": 4
      },
      {
        "id": null,
        "date": "1644154546000",
        "ref": "CHP78509185",
        "employee": "timothy.farmyard@gmail.com",
        "paymentType": "Cash",
        "amount": 8500,
        "saleType": "Entrance",
        "saleDesc": "Normal Price",
        "quantity": 1
      },
      {
        "id": null,
        "date": "1636899560000",
        "ref": "CDP65380082",
        "employee": "timothy.farmyard@gmail.com",
        "paymentType": "Card",
        "amount": 28500,
        "saleType": "Entrance",
        "saleDesc": "Normal Price",
        "quantity": 4
      },
      {
        "id": null,
        "date": "1639925702000",
        "ref": "CHP70940546",
        "employee": "timothy.farmyard@gmail.com",
        "paymentType": "Cash",
        "amount": 8500,
        "saleType": "Entrance",
        "saleDesc": "Normal Price",
        "quantity": 1
      },
      {
        "id": null,
        "date": "1644759925000",
        "ref": "CHP79444946",
        "employee": "timothy.farmyard@gmail.com",
        "paymentType": "Cash",
        "amount": 20000,
        "saleType": "Entrance",
        "saleDesc": "Normal Price",
        "quantity": 3
      },
      {
        "id": null,
        "date": "1640526048000",
        "ref": "CHP72360977",
        "employee": "timothy.farmyard@gmail.com",
        "paymentType": "Cash",
        "amount": 22000,
        "saleType": "Entrance",
        "saleDesc": "Normal Price",
        "quantity": 2
      },
      {
        "id": null,
        "date": "1619361623000",
        "ref": "CDP43146617",
        "employee": "timothy.farmyard@gmail.com",
        "paymentType": "Card",
        "amount": 53500,
        "saleType": "Entrance",
        "saleDesc": "Normal Price",
        "quantity": 7
      },
      {
        "id": null,
        "date": "1611489062000",
        "ref": "CDP35417409",
        "employee": "timothy.farmyard@gmail.com",
        "paymentType": "Card",
        "amount": 80000,
        "saleType": "Entrance",
        "saleDesc": "Discount Price",
        "quantity": 11
      },
      {
        "id": null,
        "date": "1636274069000",
        "ref": "CDP64480068",
        "employee": "timothy.farmyard@gmail.com",
        "paymentType": "Card",
        "amount": 20000,
        "saleType": "Entrance",
        "saleDesc": "Normal Price",
        "quantity": 3
      },
      {
        "id": null,
        "date": "1645975870000",
        "ref": "CHP81621923",
        "employee": "timothy.farmyard@gmail.com",
        "paymentType": "Cash",
        "amount": 557500,
        "saleType": "Entrance",
        "saleDesc": "Discount Price",
        "quantity": 89
      },
      {
        "id": null,
        "date": "1638701623000",
        "ref": "CHP68512174",
        "employee": "timothy.farmyard@gmail.com",
        "paymentType": "Cash",
        "amount": 20000,
        "saleType": "Entrance",
        "saleDesc": "Normal Price",
        "quantity": 3
      },
      {
        "id": null,
        "date": "1635691889000",
        "ref": "CHP63452558",
        "employee": "timothy.farmyard@gmail.com",
        "paymentType": "Cash",
        "amount": 29000,
        "saleType": "Entrance",
        "saleDesc": "Discount Price",
        "quantity": 5
      },
      {
        "id": null,
        "date": "1615737133000",
        "ref": "CHP39254102",
        "employee": "timothy.farmyard@gmail.com",
        "paymentType": "Cash",
        "amount": 11000,
        "saleType": "Entrance",
        "saleDesc": "Normal Price",
        "quantity": 2
      },
      {
        "id": null,
        "date": "1614528884000",
        "ref": "CHP38001656",
        "employee": "timothy.farmyard@gmail.com",
        "paymentType": "Cash",
        "amount": 8500,
        "saleType": "Entrance",
        "saleDesc": "Normal Price",
        "quantity": 1
      },
      {
        "id": null,
        "date": "1612708701000",
        "ref": "CHP36320356",
        "employee": "timothy.farmyard@gmail.com",
        "paymentType": "Cash",
        "amount": 19500,
        "saleType": "Entrance",
        "saleDesc": "Normal Price",
        "quantity": 3
      },
      {
        "id": null,
        "date": "1646578642000",
        "ref": "CDP82828639",
        "employee": "timothy.farmyard@gmail.com",
        "paymentType": "Card",
        "amount": 8500,
        "saleType": "Entrance",
        "saleDesc": "Normal Price",
        "quantity": 1
      },
      {
        "id": null,
        "date": "1648391637000",
        "ref": "CHP86140860",
        "employee": "timothy.farmyard@gmail.com",
        "paymentType": "Cash",
        "amount": 9500,
        "saleType": "Entrance",
        "saleDesc": "Discount Price",
        "quantity": 2
      },
      {
        "id": null,
        "date": "1616941239000",
        "ref": "CHP40487891",
        "employee": "timothy.farmyard@gmail.com",
        "paymentType": "Cash",
        "amount": 36500,
        "saleType": "Entrance",
        "saleDesc": "Normal Price",
        "quantity": 5
      },
      {
        "id": null,
        "date": "1648990238000",
        "ref": "CHP87409938",
        "employee": "timothy.farmyard@gmail.com",
        "paymentType": "Cash",
        "amount": 17000,
        "saleType": "Entrance",
        "saleDesc": "Normal Price",
        "quantity": 2
      },
      {
        "id": null,
        "date": "1642949269000",
        "ref": "CDP76391872",
        "employee": "timothy.farmyard@gmail.com",
        "paymentType": "Card",
        "amount": 28500,
        "saleType": "Entrance",
        "saleDesc": "Normal Price",
        "quantity": 4
      },
      {
        "id": null,
        "date": "1642345306000",
        "ref": "CHP75440148",
        "employee": "timothy.farmyard@gmail.com",
        "paymentType": "Cash",
        "amount": 20000,
        "saleType": "Entrance",
        "saleDesc": "Normal Price",
        "quantity": 3
      },
      {
        "id": null,
        "date": "1613314246000",
        "ref": "CHP36829509",
        "employee": "timothy.farmyard@gmail.com",
        "paymentType": "Cash",
        "amount": 19500,
        "saleType": "Entrance",
        "saleDesc": "Normal Price",
        "quantity": 3
      },
      {
        "id": null,
        "date": "1641135011000",
        "ref": "CDP73656220",
        "employee": "timothy.farmyard@gmail.com",
        "paymentType": "Card",
        "amount": 94000,
        "saleType": "Entrance",
        "saleDesc": "Normal Price",
        "quantity": 10
      },
      {
        "id": null,
        "date": "1617545156000",
        "ref": "CHP41281286",
        "employee": "timothy.farmyard@gmail.com",
        "paymentType": "Cash",
        "amount": 8500,
        "saleType": "Entrance",
        "saleDesc": "Normal Price",
        "quantity": 1
      }
    ]
