export const groupData = [
  {
    id: 0,
    groupName: "Church on the Rock",
    street: "34 Main Road",
    suburb: "Paarl",
  },
  {
    id: 1,
    groupName: "Church on the Rock",
    street: "34 Main Road",
    suburb: "Paarl",
  },
  {
    id: 2,
    groupName: "New Apostolic",
    street: "162 Greens Ave",
    suburb: "Bluedowns",
  },
  {
    id: 3,
    groupName: "Groen Dakkies Skill School",
    street: "Groenfontein Road",
    suburb: "Franshoek",
  },
  {
    id: 4,
    groupName: "Groen Dakkies Skill School",
    street: "Groenfontein Road",
    suburb: "Franshoek",
  },
  {
    id: 5,
    groupName: "Church on the Rock",
    street: "34 Main Road",
    suburb: "Paarl",
  },
  {
    id: 6,
    groupName: "New Apostolic",
    street: "162 Greens Ave",
    suburb: "Bluedowns",
  },
  {
    id: 7,
    groupName: "Church on the Rock",
    street: "34 Main Road",
    suburb: "Paarl",
  },
  {
    id: 8,
    groupName: "New Apostolic",
    street: "162 Greens Ave",
    suburb: "Bluedowns",
  },
  {
    id: 9,
    groupName: "Groen Dakkies Skill School",
    street: "Groenfontein Road",
    suburb: "Franshoek",
  },
  {
    id: 10,
    groupName: "Church on the Rock",
    street: "34 Main Road",
    suburb: "Paarl",
  },
  {
    id: 11,
    groupName: "Groen Dakkies Skill School",
    street: "Groenfontein Road",
    suburb: "Franshoek",
  },
  {
    id: 12,
    groupName: "New Apostolic",
    street: "162 Greens Ave",
    suburb: "Bluedowns",
  },
  {
    id: 13,
    groupName: "New Apostolic",
    street: "162 Greens Ave",
    suburb: "Bluedowns",
  },
  {
    id: 14,
    groupName: "New Apostolic",
    street: "162 Greens Ave",
    suburb: "Bluedowns",
  },
  {
    id: 15,
    groupName: "New Apostolic",
    street: "162 Greens Ave",
    suburb: "Bluedowns",
  },
  {
    id: 16,
    groupName: "Groen Dakkies Skill School",
    street: "Groenfontein Road",
    suburb: "Franshoek",
  },
  {
    id: 17,
    groupName: "Church on the Rock",
    street: "34 Main Road",
    suburb: "Paarl",
  },
  {
    id: 18,
    groupName: "Church on the Rock",
    street: "34 Main Road",
    suburb: "Paarl",
  },
  {
    id: 19,
    groupName: "Groen Dakkies Skill School",
    street: "Groenfontein Road",
    suburb: "Franshoek",
  },
  {
    id: 20,
    groupName: "Groen Dakkies Skill School",
    street: "Groenfontein Road",
    suburb: "Franshoek",
  },
  {
    id: 21,
    groupName: "New Apostolic",
    street: "162 Greens Ave",
    suburb: "Bluedowns",
  },
  {
    id: 22,
    groupName: "Groen Dakkies Skill School",
    street: "Groenfontein Road",
    suburb: "Franshoek",
  },
  {
    id: 23,
    groupName: "Church on the Rock",
    street: "34 Main Road",
    suburb: "Paarl",
  },
  {
    id: 24,
    groupName: "New Apostolic",
    street: "162 Greens Ave",
    suburb: "Bluedowns",
  },
  {
    id: 25,
    groupName: "New Apostolic",
    street: "162 Greens Ave",
    suburb: "Bluedowns",
  },
  {
    id: 26,
    groupName: "New Apostolic",
    street: "162 Greens Ave",
    suburb: "Bluedowns",
  },
  {
    id: 27,
    groupName: "Church on the Rock",
    street: "34 Main Road",
    suburb: "Paarl",
  },
  {
    id: 28,
    groupName: "Church on the Rock",
    street: "34 Main Road",
    suburb: "Paarl",
  },
  {
    id: 29,
    groupName: "Church on the Rock",
    street: "34 Main Road",
    suburb: "Paarl",
  },
  {
    id: 30,
    groupName: "New Apostolic",
    street: "162 Greens Ave",
    suburb: "Bluedowns",
  },
  {
    id: 31,
    groupName: "Groen Dakkies Skill School",
    street: "Groenfontein Road",
    suburb: "Franshoek",
  },
  {
    id: 32,
    groupName: "Church on the Rock",
    street: "34 Main Road",
    suburb: "Paarl",
  },
  {
    id: 33,
    groupName: "New Apostolic",
    street: "162 Greens Ave",
    suburb: "Bluedowns",
  },
  {
    id: 34,
    groupName: "Groen Dakkies Skill School",
    street: "Groenfontein Road",
    suburb: "Franshoek",
  },
  {
    id: 35,
    groupName: "Church on the Rock",
    street: "34 Main Road",
    suburb: "Paarl",
  },
  {
    id: 36,
    groupName: "Church on the Rock",
    street: "34 Main Road",
    suburb: "Paarl",
  },
  {
    id: 37,
    groupName: "New Apostolic",
    street: "162 Greens Ave",
    suburb: "Bluedowns",
  },
  {
    id: 38,
    groupName: "New Apostolic",
    street: "162 Greens Ave",
    suburb: "Bluedowns",
  },
  {
    id: 39,
    groupName: "Groen Dakkies Skill School",
    street: "Groenfontein Road",
    suburb: "Franshoek",
  },
  {
    id: 40,
    groupName: "New Apostolic",
    street: "162 Greens Ave",
    suburb: "Bluedowns",
  },
  {
    id: 41,
    groupName: "Church on the Rock",
    street: "34 Main Road",
    suburb: "Paarl",
  },
  {
    id: 42,
    groupName: "New Apostolic",
    street: "162 Greens Ave",
    suburb: "Bluedowns",
  },
  {
    id: 43,
    groupName: "Groen Dakkies Skill School",
    street: "Groenfontein Road",
    suburb: "Franshoek",
  },
  {
    id: 44,
    groupName: "Church on the Rock",
    street: "34 Main Road",
    suburb: "Paarl",
  },
  {
    id: 45,
    groupName: "Groen Dakkies Skill School",
    street: "Groenfontein Road",
    suburb: "Franshoek",
  },
  {
    id: 46,
    groupName: "Groen Dakkies Skill School",
    street: "Groenfontein Road",
    suburb: "Franshoek",
  },
  {
    id: 47,
    groupName: "Groen Dakkies Skill School",
    street: "Groenfontein Road",
    suburb: "Franshoek",
  },
  {
    id: 48,
    groupName: "Church on the Rock",
    street: "34 Main Road",
    suburb: "Paarl",
  },
  {
    id: 49,
    groupName: "Groen Dakkies Skill School",
    street: "Groenfontein Road",
    suburb: "Franshoek",
  },
  {
    id: 50,
    groupName: "Church on the Rock",
    street: "34 Main Road",
    suburb: "Paarl",
  },
  {
    id: 51,
    groupName: "Church on the Rock",
    street: "34 Main Road",
    suburb: "Paarl",
  },
  {
    id: 52,
    groupName: "Groen Dakkies Skill School",
    street: "Groenfontein Road",
    suburb: "Franshoek",
  },
  {
    id: 53,
    groupName: "Groen Dakkies Skill School",
    street: "Groenfontein Road",
    suburb: "Franshoek",
  },
  {
    id: 54,
    groupName: "Church on the Rock",
    street: "34 Main Road",
    suburb: "Paarl",
  },
  {
    id: 55,
    groupName: "Groen Dakkies Skill School",
    street: "Groenfontein Road",
    suburb: "Franshoek",
  },
  {
    id: 56,
    groupName: "Groen Dakkies Skill School",
    street: "Groenfontein Road",
    suburb: "Franshoek",
  },
  {
    id: 57,
    groupName: "New Apostolic",
    street: "162 Greens Ave",
    suburb: "Bluedowns",
  },
  {
    id: 58,
    groupName: "Church on the Rock",
    street: "34 Main Road",
    suburb: "Paarl",
  },
  {
    id: 59,
    groupName: "Groen Dakkies Skill School",
    street: "Groenfontein Road",
    suburb: "Franshoek",
  },
  {
    id: 60,
    groupName: "Church on the Rock",
    street: "34 Main Road",
    suburb: "Paarl",
  },
  {
    id: 61,
    groupName: "New Apostolic",
    street: "162 Greens Ave",
    suburb: "Bluedowns",
  },
  {
    id: 62,
    groupName: "New Apostolic",
    street: "162 Greens Ave",
    suburb: "Bluedowns",
  },
  {
    id: 63,
    groupName: "Church on the Rock",
    street: "34 Main Road",
    suburb: "Paarl",
  },
  {
    id: 64,
    groupName: "Church on the Rock",
    street: "34 Main Road",
    suburb: "Paarl",
  },
  {
    id: 65,
    groupName: "New Apostolic",
    street: "162 Greens Ave",
    suburb: "Bluedowns",
  },
  {
    id: 66,
    groupName: "Groen Dakkies Skill School",
    street: "Groenfontein Road",
    suburb: "Franshoek",
  },
  {
    id: 67,
    groupName: "New Apostolic",
    street: "162 Greens Ave",
    suburb: "Bluedowns",
  },
  {
    id: 68,
    groupName: "Church on the Rock",
    street: "34 Main Road",
    suburb: "Paarl",
  },
  {
    id: 69,
    groupName: "Groen Dakkies Skill School",
    street: "Groenfontein Road",
    suburb: "Franshoek",
  },
  {
    id: 70,
    groupName: "Church on the Rock",
    street: "34 Main Road",
    suburb: "Paarl",
  },
  {
    id: 71,
    groupName: "New Apostolic",
    street: "162 Greens Ave",
    suburb: "Bluedowns",
  },
  {
    id: 72,
    groupName: "Church on the Rock",
    street: "34 Main Road",
    suburb: "Paarl",
  },
  {
    id: 73,
    groupName: "New Apostolic",
    street: "162 Greens Ave",
    suburb: "Bluedowns",
  },
  {
    id: 74,
    groupName: "New Apostolic",
    street: "162 Greens Ave",
    suburb: "Bluedowns",
  },
  {
    id: 75,
    groupName: "Church on the Rock",
    street: "34 Main Road",
    suburb: "Paarl",
  },
  {
    id: 76,
    groupName: "Groen Dakkies Skill School",
    street: "Groenfontein Road",
    suburb: "Franshoek",
  },
  {
    id: 77,
    groupName: "Groen Dakkies Skill School",
    street: "Groenfontein Road",
    suburb: "Franshoek",
  },
  {
    id: 78,
    groupName: "New Apostolic",
    street: "162 Greens Ave",
    suburb: "Bluedowns",
  },
  {
    id: 79,
    groupName: "Church on the Rock",
    street: "34 Main Road",
    suburb: "Paarl",
  },
  {
    id: 80,
    groupName: "Groen Dakkies Skill School",
    street: "Groenfontein Road",
    suburb: "Franshoek",
  },
  {
    id: 81,
    groupName: "Church on the Rock",
    street: "34 Main Road",
    suburb: "Paarl",
  },
  {
    id: 82,
    groupName: "Groen Dakkies Skill School",
    street: "Groenfontein Road",
    suburb: "Franshoek",
  },
  {
    id: 83,
    groupName: "New Apostolic",
    street: "162 Greens Ave",
    suburb: "Bluedowns",
  },
  {
    id: 84,
    groupName: "Groen Dakkies Skill School",
    street: "Groenfontein Road",
    suburb: "Franshoek",
  },
  {
    id: 85,
    groupName: "New Apostolic",
    street: "162 Greens Ave",
    suburb: "Bluedowns",
  },
  {
    id: 86,
    groupName: "Church on the Rock",
    street: "34 Main Road",
    suburb: "Paarl",
  },
  {
    id: 87,
    groupName: "New Apostolic",
    street: "162 Greens Ave",
    suburb: "Bluedowns",
  },
  {
    id: 88,
    groupName: "Church on the Rock",
    street: "34 Main Road",
    suburb: "Paarl",
  },
  {
    id: 89,
    groupName: "Church on the Rock",
    street: "34 Main Road",
    suburb: "Paarl",
  },
  {
    id: 90,
    groupName: "Groen Dakkies Skill School",
    street: "Groenfontein Road",
    suburb: "Franshoek",
  },
  {
    id: 91,
    groupName: "New Apostolic",
    street: "162 Greens Ave",
    suburb: "Bluedowns",
  },
  {
    id: 92,
    groupName: "New Apostolic",
    street: "162 Greens Ave",
    suburb: "Bluedowns",
  },
  {
    id: 93,
    groupName: "New Apostolic",
    street: "162 Greens Ave",
    suburb: "Bluedowns",
  },
  {
    id: 94,
    groupName: "Church on the Rock",
    street: "34 Main Road",
    suburb: "Paarl",
  },
  {
    id: 95,
    groupName: "Groen Dakkies Skill School",
    street: "Groenfontein Road",
    suburb: "Franshoek",
  },
  {
    id: 96,
    groupName: "Church on the Rock",
    street: "34 Main Road",
    suburb: "Paarl",
  },
  {
    id: 97,
    groupName: "Groen Dakkies Skill School",
    street: "Groenfontein Road",
    suburb: "Franshoek",
  },
  {
    id: 98,
    groupName: "Groen Dakkies Skill School",
    street: "Groenfontein Road",
    suburb: "Franshoek",
  },
  {
    id: 99,
    groupName: "Groen Dakkies Skill School",
    street: "Groenfontein Road",
    suburb: "Franshoek",
  },
  {
    id: 100,
    groupName: "Groen Dakkies Skill School",
    street: "Groenfontein Road",
    suburb: "Franshoek",
  },
  {
    id: 101,
    groupName: "Groen Dakkies Skill School",
    street: "Groenfontein Road",
    suburb: "Franshoek",
  },
  {
    id: 102,
    groupName: "Church on the Rock",
    street: "34 Main Road",
    suburb: "Paarl",
  },
  {
    id: 103,
    groupName: "Church on the Rock",
    street: "34 Main Road",
    suburb: "Paarl",
  },
  {
    id: 104,
    groupName: "Church on the Rock",
    street: "34 Main Road",
    suburb: "Paarl",
  },
  {
    id: 105,
    groupName: "Church on the Rock",
    street: "34 Main Road",
    suburb: "Paarl",
  },
  {
    id: 106,
    groupName: "Groen Dakkies Skill School",
    street: "Groenfontein Road",
    suburb: "Franshoek",
  },
  {
    id: 107,
    groupName: "Church on the Rock",
    street: "34 Main Road",
    suburb: "Paarl",
  },
  {
    id: 108,
    groupName: "Church on the Rock",
    street: "34 Main Road",
    suburb: "Paarl",
  },
  {
    id: 109,
    groupName: "Groen Dakkies Skill School",
    street: "Groenfontein Road",
    suburb: "Franshoek",
  },
  {
    id: 110,
    groupName: "New Apostolic",
    street: "162 Greens Ave",
    suburb: "Bluedowns",
  },
  {
    id: 111,
    groupName: "Groen Dakkies Skill School",
    street: "Groenfontein Road",
    suburb: "Franshoek",
  },
  {
    id: 112,
    groupName: "Church on the Rock",
    street: "34 Main Road",
    suburb: "Paarl",
  },
  {
    id: 113,
    groupName: "Church on the Rock",
    street: "34 Main Road",
    suburb: "Paarl",
  },
  {
    id: 114,
    groupName: "Groen Dakkies Skill School",
    street: "Groenfontein Road",
    suburb: "Franshoek",
  },
  {
    id: 115,
    groupName: "Church on the Rock",
    street: "34 Main Road",
    suburb: "Paarl",
  },
  {
    id: 116,
    groupName: "Church on the Rock",
    street: "34 Main Road",
    suburb: "Paarl",
  },
  {
    id: 117,
    groupName: "New Apostolic",
    street: "162 Greens Ave",
    suburb: "Bluedowns",
  },
  {
    id: 118,
    groupName: "Church on the Rock",
    street: "34 Main Road",
    suburb: "Paarl",
  },
  {
    id: 119,
    groupName: "Church on the Rock",
    street: "34 Main Road",
    suburb: "Paarl",
  },
  {
    id: 120,
    groupName: "New Apostolic",
    street: "162 Greens Ave",
    suburb: "Bluedowns",
  },
  {
    id: 121,
    groupName: "Groen Dakkies Skill School",
    street: "Groenfontein Road",
    suburb: "Franshoek",
  },
  {
    id: 122,
    groupName: "Church on the Rock",
    street: "34 Main Road",
    suburb: "Paarl",
  },
  {
    id: 123,
    groupName: "Church on the Rock",
    street: "34 Main Road",
    suburb: "Paarl",
  },
  {
    id: 124,
    groupName: "Groen Dakkies Skill School",
    street: "Groenfontein Road",
    suburb: "Franshoek",
  },
  {
    id: 125,
    groupName: "New Apostolic",
    street: "162 Greens Ave",
    suburb: "Bluedowns",
  },
  {
    id: 126,
    groupName: "Church on the Rock",
    street: "34 Main Road",
    suburb: "Paarl",
  },
  {
    id: 127,
    groupName: "Church on the Rock",
    street: "34 Main Road",
    suburb: "Paarl",
  },
  {
    id: 128,
    groupName: "Church on the Rock",
    street: "34 Main Road",
    suburb: "Paarl",
  },
  {
    id: 129,
    groupName: "Church on the Rock",
    street: "34 Main Road",
    suburb: "Paarl",
  },
  {
    id: 130,
    groupName: "Groen Dakkies Skill School",
    street: "Groenfontein Road",
    suburb: "Franshoek",
  },
  {
    id: 131,
    groupName: "New Apostolic",
    street: "162 Greens Ave",
    suburb: "Bluedowns",
  },
  {
    id: 132,
    groupName: "Church on the Rock",
    street: "34 Main Road",
    suburb: "Paarl",
  },
  {
    id: 133,
    groupName: "New Apostolic",
    street: "162 Greens Ave",
    suburb: "Bluedowns",
  },
  {
    id: 134,
    groupName: "Church on the Rock",
    street: "34 Main Road",
    suburb: "Paarl",
  },
  {
    id: 135,
    groupName: "Groen Dakkies Skill School",
    street: "Groenfontein Road",
    suburb: "Franshoek",
  },
  {
    id: 136,
    groupName: "Church on the Rock",
    street: "34 Main Road",
    suburb: "Paarl",
  },
  {
    id: 137,
    groupName: "New Apostolic",
    street: "162 Greens Ave",
    suburb: "Bluedowns",
  },
  {
    id: 138,
    groupName: "Groen Dakkies Skill School",
    street: "Groenfontein Road",
    suburb: "Franshoek",
  },
  {
    id: 139,
    groupName: "Church on the Rock",
    street: "34 Main Road",
    suburb: "Paarl",
  },
  {
    id: 140,
    groupName: "Church on the Rock",
    street: "34 Main Road",
    suburb: "Paarl",
  },
  {
    id: 141,
    groupName: "Groen Dakkies Skill School",
    street: "Groenfontein Road",
    suburb: "Franshoek",
  },
  {
    id: 142,
    groupName: "Groen Dakkies Skill School",
    street: "Groenfontein Road",
    suburb: "Franshoek",
  },
  {
    id: 143,
    groupName: "New Apostolic",
    street: "162 Greens Ave",
    suburb: "Bluedowns",
  },
  {
    id: 144,
    groupName: "Church on the Rock",
    street: "34 Main Road",
    suburb: "Paarl",
  },
  {
    id: 145,
    groupName: "Church on the Rock",
    street: "34 Main Road",
    suburb: "Paarl",
  },
  {
    id: 146,
    groupName: "New Apostolic",
    street: "162 Greens Ave",
    suburb: "Bluedowns",
  },
  {
    id: 147,
    groupName: "Groen Dakkies Skill School",
    street: "Groenfontein Road",
    suburb: "Franshoek",
  },
  {
    id: 148,
    groupName: "New Apostolic",
    street: "162 Greens Ave",
    suburb: "Bluedowns",
  },
  {
    id: 149,
    groupName: "New Apostolic",
    street: "162 Greens Ave",
    suburb: "Bluedowns",
  },
  {
    id: 150,
    groupName: "Groen Dakkies Skill School",
    street: "Groenfontein Road",
    suburb: "Franshoek",
  },
  {
    id: 151,
    groupName: "Groen Dakkies Skill School",
    street: "Groenfontein Road",
    suburb: "Franshoek",
  },
  {
    id: 152,
    groupName: "Church on the Rock",
    street: "34 Main Road",
    suburb: "Paarl",
  },
  {
    id: 153,
    groupName: "New Apostolic",
    street: "162 Greens Ave",
    suburb: "Bluedowns",
  },
  {
    id: 154,
    groupName: "New Apostolic",
    street: "162 Greens Ave",
    suburb: "Bluedowns",
  },
  {
    id: 155,
    groupName: "Groen Dakkies Skill School",
    street: "Groenfontein Road",
    suburb: "Franshoek",
  },
  {
    id: 156,
    groupName: "Church on the Rock",
    street: "34 Main Road",
    suburb: "Paarl",
  },
  {
    id: 157,
    groupName: "Groen Dakkies Skill School",
    street: "Groenfontein Road",
    suburb: "Franshoek",
  },
  {
    id: 158,
    groupName: "Groen Dakkies Skill School",
    street: "Groenfontein Road",
    suburb: "Franshoek",
  },
  {
    id: 159,
    groupName: "Church on the Rock",
    street: "34 Main Road",
    suburb: "Paarl",
  },
  {
    id: 160,
    groupName: "Groen Dakkies Skill School",
    street: "Groenfontein Road",
    suburb: "Franshoek",
  },
  {
    id: 161,
    groupName: "New Apostolic",
    street: "162 Greens Ave",
    suburb: "Bluedowns",
  },
  {
    id: 162,
    groupName: "New Apostolic",
    street: "162 Greens Ave",
    suburb: "Bluedowns",
  },
  {
    id: 163,
    groupName: "Church on the Rock",
    street: "34 Main Road",
    suburb: "Paarl",
  },
  {
    id: 164,
    groupName: "Church on the Rock",
    street: "34 Main Road",
    suburb: "Paarl",
  },
  {
    id: 165,
    groupName: "New Apostolic",
    street: "162 Greens Ave",
    suburb: "Bluedowns",
  },
  {
    id: 166,
    groupName: "Groen Dakkies Skill School",
    street: "Groenfontein Road",
    suburb: "Franshoek",
  },
  {
    id: 167,
    groupName: "Groen Dakkies Skill School",
    street: "Groenfontein Road",
    suburb: "Franshoek",
  },
  {
    id: 168,
    groupName: "Church on the Rock",
    street: "34 Main Road",
    suburb: "Paarl",
  },
  {
    id: 169,
    groupName: "Church on the Rock",
    street: "34 Main Road",
    suburb: "Paarl",
  },
  {
    id: 170,
    groupName: "Groen Dakkies Skill School",
    street: "Groenfontein Road",
    suburb: "Franshoek",
  },
  {
    id: 171,
    groupName: "Groen Dakkies Skill School",
    street: "Groenfontein Road",
    suburb: "Franshoek",
  },
  {
    id: 172,
    groupName: "Church on the Rock",
    street: "34 Main Road",
    suburb: "Paarl",
  },
  {
    id: 173,
    groupName: "Groen Dakkies Skill School",
    street: "Groenfontein Road",
    suburb: "Franshoek",
  },
  {
    id: 174,
    groupName: "Groen Dakkies Skill School",
    street: "Groenfontein Road",
    suburb: "Franshoek",
  },
  {
    id: 175,
    groupName: "Groen Dakkies Skill School",
    street: "Groenfontein Road",
    suburb: "Franshoek",
  },
  {
    id: 176,
    groupName: "Church on the Rock",
    street: "34 Main Road",
    suburb: "Paarl",
  },
  {
    id: 177,
    groupName: "Church on the Rock",
    street: "34 Main Road",
    suburb: "Paarl",
  },
  {
    id: 178,
    groupName: "Church on the Rock",
    street: "34 Main Road",
    suburb: "Paarl",
  },
  {
    id: 179,
    groupName: "Groen Dakkies Skill School",
    street: "Groenfontein Road",
    suburb: "Franshoek",
  },
  {
    id: 180,
    groupName: "Groen Dakkies Skill School",
    street: "Groenfontein Road",
    suburb: "Franshoek",
  },
  {
    id: 181,
    groupName: "Groen Dakkies Skill School",
    street: "Groenfontein Road",
    suburb: "Franshoek",
  },
  {
    id: 182,
    groupName: "Church on the Rock",
    street: "34 Main Road",
    suburb: "Paarl",
  },
  {
    id: 183,
    groupName: "New Apostolic",
    street: "162 Greens Ave",
    suburb: "Bluedowns",
  },
  {
    id: 184,
    groupName: "Groen Dakkies Skill School",
    street: "Groenfontein Road",
    suburb: "Franshoek",
  },
  {
    id: 185,
    groupName: "Church on the Rock",
    street: "34 Main Road",
    suburb: "Paarl",
  },
  {
    id: 186,
    groupName: "Groen Dakkies Skill School",
    street: "Groenfontein Road",
    suburb: "Franshoek",
  },
  {
    id: 187,
    groupName: "New Apostolic",
    street: "162 Greens Ave",
    suburb: "Bluedowns",
  },
  {
    id: 188,
    groupName: "New Apostolic",
    street: "162 Greens Ave",
    suburb: "Bluedowns",
  },
  {
    id: 189,
    groupName: "New Apostolic",
    street: "162 Greens Ave",
    suburb: "Bluedowns",
  },
  {
    id: 190,
    groupName: "New Apostolic",
    street: "162 Greens Ave",
    suburb: "Bluedowns",
  },
  {
    id: 191,
    groupName: "New Apostolic",
    street: "162 Greens Ave",
    suburb: "Bluedowns",
  },
  {
    id: 192,
    groupName: "Church on the Rock",
    street: "34 Main Road",
    suburb: "Paarl",
  },
  {
    id: 193,
    groupName: "Groen Dakkies Skill School",
    street: "Groenfontein Road",
    suburb: "Franshoek",
  },
  {
    id: 194,
    groupName: "Groen Dakkies Skill School",
    street: "Groenfontein Road",
    suburb: "Franshoek",
  },
  {
    id: 195,
    groupName: "Church on the Rock",
    street: "34 Main Road",
    suburb: "Paarl",
  },
  {
    id: 196,
    groupName: "Groen Dakkies Skill School",
    street: "Groenfontein Road",
    suburb: "Franshoek",
  },
  {
    id: 197,
    groupName: "Church on the Rock",
    street: "34 Main Road",
    suburb: "Paarl",
  },
  {
    id: 198,
    groupName: "Groen Dakkies Skill School",
    street: "Groenfontein Road",
    suburb: "Franshoek",
  },
  {
    id: 199,
    groupName: "Groen Dakkies Skill School",
    street: "Groenfontein Road",
    suburb: "Franshoek",
  },
];
